### ISSUE TITLE
Error running conversion

### ISSUE THREAD

**Issue by jfiala** [kubamarchwicki/asciidoctor-fodt#10]
I tried running the converter on Ubuntu 12:

asciidoctor -T asciidoctor-fodt-master/slim -b fodt test.adoc
asciidoctor: WARNING: gem 'thread_safe' is not installed. This gem is recommended when using custom backend templates.
asciidoctor: FAILED: /root/asciidoctor/asciidoctor-fodt/test.adoc: Failed to load AsciiDoc document - asciidoctor: FAILED: required gem 'slim' is not installed. Processing aborted. (RuntimeError)
  Use --trace for backtrace

It seems that asciidoctor is unable to locate the gem 'slim', although it is installed (using .gem install slim).

I made sure it is available in Ruby:
irb
irb(main):001:0> require 'slim'
=> true

Please advise how to configure asciidoctor so it is able to find the required slim module?

Thank you & Best regards,
Johannes

**Comment by kubamarchwicki** [comment]
Hi Johannes,
There is a gem **thread_safe** which is also needed. I've created a new ruby environment from scratch and installed following gems:
- asciidoctor
- titl
- thread_safe
- slim

and conversion went through. The above gems are required (though I'm not feeling very good giving a ruby advice, being a kind of ruby nob myself). 
Anyway - hope that helps

Also, please mind the ODT backend is still very early development phase, and not all templates are implemented (and some are implemented as a kind of MVP required by myself). If you lack something please let me know - I'm happy to collaborate and drag take the backend forward. 

Jakub
